const ACTIVITY_ACTIONS = {
  // Project actions
  CREATE_PROJECT: "CREATE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  COMPLETE_PROJECT: "COMPLETE_PROJECT",
  ASSIGN_PROJECT_COORDINATOR: "ASSIGN_PROJECT_COORDINATOR",

  // Task actions
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  COMPLETE_TASK: "COMPLETE_TASK",
  ASSIGN_TASK: "ASSIGN_TASK",
  DELETE_TASK: "DELETE_TASK",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_MOVED_TO_REVIEW: "TASK_MOVED_TO_REVIEW",
  TASK_APPROVED: "TASK_APPROVED",
  TASK_REJECTED: "TASK_REJECTED",
  TASK_ATTACHMENT_UPLOADED: "TASK_ATTACHMENT_UPLOADED",
  TASK_ATTACHMENT_DELETED: "TASK_ATTACHMENT_DELETED",
  TASK_COMMENT_ADDED: "TASK_COMMENT_ADDED",
  TASK_CHECKLIST_UPDATED: "TASK_CHECKLIST_UPDATED",
  TASK_ESTIMATED_HOURS_UPDATED: "TASK_ESTIMATED_HOURS_UPDATED",
  
  // Document actions
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  UPLOAD_DOCUMENT_VERSION: "UPLOAD_DOCUMENT_VERSION",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  DOWNLOAD_DOCUMENT: "DOWNLOAD_DOCUMENT",
  
  // Event actions
  CREATE_EVENT: "CREATE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  DELETE_EVENT: "DELETE_EVENT",
  JOIN_EVENT: "JOIN_EVENT",
  
  // User actions
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  
  // Chat and Message actions
  SEND_MESSAGE: "SEND_MESSAGE",
  CREATE_CHAT: "CREATE_CHAT",
  JOIN_CHAT: "JOIN_CHAT",
  
  // Invitation actions
  CREATE_INVITATION: "CREATE_INVITATION",
  ACCEPT_INVITATION: "ACCEPT_INVITATION",
  
  // System actions
  SYSTEM_BACKUP: "SYSTEM_BACKUP",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
};

const ACTIVITY_ENTITIES = {
  PROJECT: "PROJECT",
  TASK: "TASK",
  DOCUMENT: "DOCUMENT",
  EVENT: "EVENT",
  USER: "USER",
  CHAT: "CHAT",
  MESSAGE: "MESSAGE",
  INVITATION: "INVITATION",
  SYSTEM: "SYSTEM",
};

module.exports = {
  ACTIVITY_ACTIONS,
  ACTIVITY_ENTITIES,
};
