const CHAT_TYPES = {
  PROJECT: "PROJECT",
  TASK: "TASK",
  TEAM: "TEAM"
};

const NOTIFICATION_TYPES = {
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED"
};

const SOCKET_EVENTS = {
  JOIN_CHAT: "joinChat",
  LEAVE_CHAT: "leaveChat",
  SEND_MESSAGE: "sendMessage",
  NEW_MESSAGE: "newMessage",
  NOTIFICATION: "notification",
  USER_CONNECTED: "userConnected",
  USER_DISCONNECTED: "userDisconnected"
};

const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100
};

module.exports = {
  CHAT_TYPES,
  NOTIFICATION_TYPES,
  SOCKET_EVENTS,
  PAGINATION_DEFAULTS,
};
