const { 
  USER_ROLES, 
  VALID_INVITATION_ROLES, 
  VALID_REGISTER_ROLES_WITHOUT_INVITATION, 
  VALID_REGISTER_ROLES_WITH_INVITATION 
} = require('./roles');

const INVITATION_EXPIRY_HOURS = 48;

const {
  CHAT_TYPES,
  NOTIFICATION_TYPES,
  SOCKET_EVENTS,
  PAGINATION_DEFAULTS,
} = require('./chat');

module.exports = {
  USER_ROLES,
  VALID_INVITATION_ROLES,
  VALID_REGISTER_ROLES_WITHOUT_INVITATION,
  VALID_REGISTER_ROLES_WITH_INVITATION,
  INVITATION_EXPIRY_HOURS,
  CHAT_TYPES,
  NOTIFICATION_TYPES,
  SOCKET_EVENTS,
  PAGINATION_DEFAULTS,
};
