const {
  USER_ROLES,
  VALID_INVITATION_ROLES,
  VALID_REGISTER_ROLES_WITHOUT_INVITATION,
  VALID_REGISTER_ROLES_WITH_INVITATION
} = require('./roles');

const INVITATION_EXPIRY_HOURS = 48;

const {
  CHAT_TYPES,
  SOCKET_EVENTS,
  PAGINATION_DEFAULTS,
  DIRECT_MESSAGE_MATRIX,
  getMessageableRoles,
  canDirectMessage,
} = require('./chat');

const {
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CATEGORY_BY_TYPE,
  NOTIFICATION_DEFAULT_PRIORITY,
  getNotificationCategory,
  getDefaultPriority,
} = require('./notifications');

module.exports = {
  USER_ROLES,
  VALID_INVITATION_ROLES,
  VALID_REGISTER_ROLES_WITHOUT_INVITATION,
  VALID_REGISTER_ROLES_WITH_INVITATION,
  INVITATION_EXPIRY_HOURS,
  CHAT_TYPES,
  SOCKET_EVENTS,
  PAGINATION_DEFAULTS,
  DIRECT_MESSAGE_MATRIX,
  getMessageableRoles,
  canDirectMessage,
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CATEGORY_BY_TYPE,
  NOTIFICATION_DEFAULT_PRIORITY,
  getNotificationCategory,
  getDefaultPriority,
};
