// ─── Notification type registry ──────────────────────────────────────────────
// Workflow-driven, role-aware notifications across the research platform.
const NOTIFICATION_TYPES = {
  // Task lifecycle
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_OVERDUE: "TASK_OVERDUE",
  TASK_COMPLETED: "TASK_COMPLETED",

  // Review workflow
  REVIEW_SUBMITTED: "REVIEW_SUBMITTED",
  REVIEW_APPROVED: "REVIEW_APPROVED",
  REVIEW_REJECTED: "REVIEW_REJECTED",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",

  // Deliverable activity
  DELIVERABLE_UPLOADED: "DELIVERABLE_UPLOADED",
  DELIVERABLE_VERSION_UPLOADED: "DELIVERABLE_VERSION_UPLOADED",
  DELIVERABLE_APPROVED: "DELIVERABLE_APPROVED",
  DELIVERABLE_REJECTED: "DELIVERABLE_REJECTED",
  DELIVERABLE_DELETED: "DELIVERABLE_DELETED",

  // Project events
  PROJECT_ASSIGNED: "PROJECT_ASSIGNED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",

  // System events
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  USER_INVITED: "USER_INVITED",
  PROFILE_UPDATED: "PROFILE_UPDATED",

  // Legacy — retained for the chat notification path.
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
};

const NOTIFICATION_PRIORITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

// Categories drive the frontend filter tabs.
const NOTIFICATION_CATEGORIES = {
  TASK: "TASK",
  REVIEW: "REVIEW",
  DELIVERABLE: "DELIVERABLE",
  PROJECT: "PROJECT",
  CHAT: "CHAT",
  SYSTEM: "SYSTEM",
};

const T = NOTIFICATION_TYPES;

// Maps each type to the category used by filtering.
const NOTIFICATION_CATEGORY_BY_TYPE = {
  [T.TASK_ASSIGNED]: NOTIFICATION_CATEGORIES.TASK,
  [T.TASK_UPDATED]: NOTIFICATION_CATEGORIES.TASK,
  [T.TASK_STATUS_CHANGED]: NOTIFICATION_CATEGORIES.TASK,
  [T.TASK_OVERDUE]: NOTIFICATION_CATEGORIES.TASK,
  [T.TASK_COMPLETED]: NOTIFICATION_CATEGORIES.TASK,

  [T.REVIEW_SUBMITTED]: NOTIFICATION_CATEGORIES.REVIEW,
  [T.REVIEW_APPROVED]: NOTIFICATION_CATEGORIES.REVIEW,
  [T.REVIEW_REJECTED]: NOTIFICATION_CATEGORIES.REVIEW,
  [T.CHANGES_REQUESTED]: NOTIFICATION_CATEGORIES.REVIEW,

  [T.DELIVERABLE_UPLOADED]: NOTIFICATION_CATEGORIES.DELIVERABLE,
  [T.DELIVERABLE_VERSION_UPLOADED]: NOTIFICATION_CATEGORIES.DELIVERABLE,
  [T.DELIVERABLE_APPROVED]: NOTIFICATION_CATEGORIES.DELIVERABLE,
  [T.DELIVERABLE_REJECTED]: NOTIFICATION_CATEGORIES.DELIVERABLE,
  [T.DELIVERABLE_DELETED]: NOTIFICATION_CATEGORIES.DELIVERABLE,

  [T.PROJECT_ASSIGNED]: NOTIFICATION_CATEGORIES.PROJECT,
  [T.PROJECT_UPDATED]: NOTIFICATION_CATEGORIES.PROJECT,
  [T.PROJECT_COMPLETED]: NOTIFICATION_CATEGORIES.PROJECT,
  [T.PROJECT_ARCHIVED]: NOTIFICATION_CATEGORIES.PROJECT,

  [T.PASSWORD_CHANGED]: NOTIFICATION_CATEGORIES.SYSTEM,
  [T.USER_INVITED]: NOTIFICATION_CATEGORIES.SYSTEM,
  [T.PROFILE_UPDATED]: NOTIFICATION_CATEGORIES.SYSTEM,
  [T.MESSAGE_RECEIVED]: NOTIFICATION_CATEGORIES.CHAT,
  [T.DOCUMENT_UPLOADED]: NOTIFICATION_CATEGORIES.PROJECT,
};

const P = NOTIFICATION_PRIORITIES;

// Default priority per type — callers may override.
const NOTIFICATION_DEFAULT_PRIORITY = {
  [T.TASK_ASSIGNED]: P.HIGH,
  [T.TASK_UPDATED]: P.LOW,
  [T.TASK_STATUS_CHANGED]: P.MEDIUM,
  [T.TASK_OVERDUE]: P.CRITICAL,
  [T.TASK_COMPLETED]: P.MEDIUM,

  [T.REVIEW_SUBMITTED]: P.HIGH,
  [T.REVIEW_APPROVED]: P.MEDIUM,
  [T.REVIEW_REJECTED]: P.HIGH,
  [T.CHANGES_REQUESTED]: P.HIGH,

  [T.DELIVERABLE_UPLOADED]: P.MEDIUM,
  [T.DELIVERABLE_VERSION_UPLOADED]: P.MEDIUM,
  [T.DELIVERABLE_APPROVED]: P.MEDIUM,
  [T.DELIVERABLE_REJECTED]: P.HIGH,
  [T.DELIVERABLE_DELETED]: P.LOW,

  [T.PROJECT_ASSIGNED]: P.HIGH,
  [T.PROJECT_UPDATED]: P.LOW,
  [T.PROJECT_COMPLETED]: P.MEDIUM,
  [T.PROJECT_ARCHIVED]: P.MEDIUM,

  [T.PASSWORD_CHANGED]: P.HIGH,
  [T.USER_INVITED]: P.LOW,
  [T.PROFILE_UPDATED]: P.LOW,
  [T.MESSAGE_RECEIVED]: P.LOW,
  [T.DOCUMENT_UPLOADED]: P.LOW,
};

function getNotificationCategory(type) {
  return NOTIFICATION_CATEGORY_BY_TYPE[type] || NOTIFICATION_CATEGORIES.SYSTEM;
}

function getDefaultPriority(type) {
  return NOTIFICATION_DEFAULT_PRIORITY[type] || NOTIFICATION_PRIORITIES.MEDIUM;
}

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CATEGORY_BY_TYPE,
  NOTIFICATION_DEFAULT_PRIORITY,
  getNotificationCategory,
  getDefaultPriority,
};
