const USER_ROLES = {
  ADMIN: "admin",
  COORDINATOR: "coordinator", 
  PRINCIPAL: "principal",
  CORESEARCHER: "co-researcher"
};

const VALID_INVITATION_ROLES = [
  USER_ROLES.ADMIN,
  USER_ROLES.COORDINATOR,
  USER_ROLES.PRINCIPAL,
  USER_ROLES.CORESEARCHER
];

const VALID_REGISTER_ROLES_WITHOUT_INVITATION = [USER_ROLES.ADMIN];

const VALID_REGISTER_ROLES_WITH_INVITATION = [
  USER_ROLES.COORDINATOR,
  USER_ROLES.PRINCIPAL,
  USER_ROLES.CORESEARCHER
];

module.exports = {
  USER_ROLES,
  VALID_INVITATION_ROLES,
  VALID_REGISTER_ROLES_WITHOUT_INVITATION,
  VALID_REGISTER_ROLES_WITH_INVITATION,
};
