const mongoose = require("mongoose");
const Project = require("../models/project");
const Task = require("../models/Task");

/**
 * BUSINESS RULE — STRICT PERSONAL EXECUTION SCOPE:
 *   The Co-Researcher Dashboard shows ONLY tasks assigned directly to the logged-in
 *   Co-Researcher. It is a PERSONAL execution dashboard, NOT a team analytics or
 *   project supervision dashboard.
 *
 * FILTERING RULES:
 *   ✓ Only tasks where assignedTo === currentUser._id
 *   ✓ Only tasks where project.isDeleted === false
 *   ✓ Only tasks where task.isDeleted === false
 *   ✗ Never include tasks from principal
 *   ✗ Never include tasks from other co-researchers
 *   ✗ Never include global metrics
 *   ✗ Never include coordinator metrics
 *   ✗ Never include unrelated workflow activity
 */

/**
 * Get all projects where the logged-in user is an assigned Co-Researcher.
 * Used to scope project-related data on the Co-Researcher dashboard.
 */
const getCoResearcherProjects = async (req) => {
  const { userId, organization } = req.user;
  return Project.find({
    organization,
    coResearchers: userId,
    isDeleted: false,
  }).select("_id");
};

/**
 * Build the canonical task-scope query for the Co-Researcher Dashboard.
 * MUST filter by: assignedTo === currentUser._id
 */
const buildCoResearcherTaskQuery = (req, _projectIds, extra = {}) => {
  const { userId, organization } = req.user;
  return {
    organization,
    isDeleted: false,
    assignedTo: userId,
    ...extra,
  };
};

/**
 * GET /api/co-researcher/dashboard/overview
 * Return personal task statistics filtered by current co-researcher.
 */
exports.getOverview = async (req, res) => {
  try {
    const { organization } = req.user;
    const projects = await getCoResearcherProjects(req);
    const projectIds = projects.map((p) => p._id);

    // Restrict every counter to tasks whose parent project is still alive,
    // so KPI counts stay consistent with /activity (which strips orphans).
    const aliveProjects = await Project.find({ organization, isDeleted: false }).select("_id");
    const aliveProjectIds = aliveProjects.map((p) => p._id);

    // Co-Researcher-scoped base query: ONLY tasks directly assigned to this Co-Researcher
    // AND whose project is not soft-deleted.
    const baseQuery = {
      ...buildCoResearcherTaskQuery(req, projectIds),
      project: { $in: aliveProjectIds },
    };

    const [
      myTasks, activeTasksCount, pendingReviewsCount,
      changesRequestedCount, overdueTasksCount, completedTasksCount,
    ] = await Promise.all([
      Task.countDocuments(baseQuery),
      Task.countDocuments({ ...baseQuery, status: "in-progress" }),
      Task.countDocuments({ ...baseQuery, status: "review" }),
      Task.countDocuments({ ...baseQuery, status: "changes-requested" }),
      Task.countDocuments({
        ...baseQuery,
        status: { $nin: ["done", "cancelled"] },
        dueDate: { $lt: new Date() },
      }),
      Task.countDocuments({ ...baseQuery, status: "done" }),
    ]);

    res.json({
      success: true,
      data: {
        myTasks,
        activeTasksCount,
        pendingReviewsCount,
        changesRequestedCount,
        overdueTasksCount,
        completedTasksCount,
      },
    });
  } catch (error) {
    console.error("Error fetching co-researcher overview:", error);
    res.status(500).json({ success: false, message: "Error fetching co-researcher overview" });
  }
};

/**
 * GET /api/co-researcher/dashboard/activity
 * Return recent workflow activity generated by the current co-researcher only.
 */
exports.getActivity = async (req, res) => {
  try {
    const { organization } = req.user;
    const projects = await getCoResearcherProjects(req);
    const projectIds = projects.map((p) => p._id);

    // Pre-filter to alive projects so activity stays consistent with overview KPIs
    const aliveProjects = await Project.find({ organization, isDeleted: false }).select("_id");
    const aliveProjectIds = aliveProjects.map((p) => p._id);

    const query = {
      ...buildCoResearcherTaskQuery(req, projectIds),
      project: { $in: aliveProjectIds },
    };

    const recentTasks = await Task.find(query)
      .populate({ path: "assignedTo", select: "name email" })
      .populate({ path: "project", select: "title", match: { isDeleted: false } })
      .sort({ updatedAt: -1 })
      .limit(20)
      .select("title status dueDate priority assignedTo project updatedAt");

    // Defensive: drop any task whose project resolved to null (race-condition safe)
    const validTasks = recentTasks.filter((t) => t.project !== null);

    const data = validTasks.map((t) => ({
      _id: t._id,
      type:
        t.status === "review"
          ? "review_requested"
          : t.status === "done"
            ? "task_completed"
            : t.status === "changes-requested"
              ? "changes_requested"
              : "task_updated",
      title: t.title,
      status: t.status,
      priority: t.priority,
      dueDate: t.dueDate,
      project: t.project,
      assignedTo: t.assignedTo,
      updatedAt: t.updatedAt,
    }));

    res.json({ success: true, data });
  } catch (error) {
    console.error("Error fetching co-researcher activity:", error);
    res.status(500).json({ success: false, message: "Error fetching co-researcher activity" });
  }
};
