const fs = require("fs");
const PDFDocument = require("pdfkit");
const ExcelJS = require("exceljs");

// ─── Shared palette ──────────────────────────────────────────────────────────
const COLORS = {
  primary: "#6366F1",
  purple: "#8B5CF6",
  green: "#10B981",
  red: "#EF4444",
  amber: "#F59E0B",
  cyan: "#06B6D4",
  ink: "#0F1923",
  muted: "#6B7280",
  line: "#E5E7EB",
};

const TYPE_LABELS = {
  executive: "Executive Summary",
  "project-progress": "Project Progress Report",
  "deliverable-summary": "Deliverable Summary",
  "researcher-performance": "Researcher Performance",
  "activity-audit": "Activity Audit",
  "overdue-analysis": "Overdue Analysis",
};

function fmtDate(d) {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function rangeLabel(dateRange = {}) {
  if (!dateRange.startDate && !dateRange.endDate) return "All time";
  return `${fmtDate(dateRange.startDate)} → ${fmtDate(dateRange.endDate)}`;
}

// ════════════════════════════════════════════════════════════════════════════
// PDF GENERATION (pdfkit)
// ════════════════════════════════════════════════════════════════════════════

function buildReportPdf(filePath, ctx) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
    const stream = fs.createWriteStream(filePath);

    stream.on("finish", resolve);
    stream.on("error", reject);
    doc.on("error", reject);
    doc.pipe(stream);

    drawPdfHeader(doc, ctx);
    drawPdfKpis(doc, ctx.metrics);
    drawPdfMetricsTable(doc, ctx.metrics);
    drawPdfBarChart(
      doc,
      "Task Status Distribution",
      taskStatusBars(ctx.data.tasks)
    );

    if (ctx.type === "overdue-analysis" || ctx.type === "executive") {
      drawPdfOverdue(doc, ctx.data.tasks);
    }
    if (ctx.type === "deliverable-summary" || ctx.type === "executive") {
      drawPdfDeliverables(doc, ctx.data.deliverables);
    }
    if (ctx.type === "researcher-performance" || ctx.type === "executive") {
      drawPdfResearchers(doc, ctx.charts.researcherProductivity);
    }
    if (ctx.type === "activity-audit" || ctx.type === "executive") {
      drawPdfActivity(doc, ctx.data.activityLogs);
    }
    if (ctx.type === "project-progress") {
      drawPdfProjects(doc, ctx.data.projects);
    }

    drawPdfFooter(doc);
    doc.end();
  });
}

function drawPdfHeader(doc, ctx) {
  const top = 50;
  doc.rect(50, top, 495, 70).fill(COLORS.primary);
  doc
    .fillColor("#FFFFFF")
    .fontSize(20)
    .font("Helvetica-Bold")
    .text(ctx.title || "Report", 66, top + 14);
  doc
    .fontSize(10)
    .font("Helvetica")
    .text(
      `${TYPE_LABELS[ctx.type] || ctx.type}  ·  Range: ${rangeLabel(
        ctx.dateRange
      )}`,
      66,
      top + 40
    );
  doc.text(
    `Generated by ${ctx.generatedBy || "Admin"} on ${fmtDate(new Date())}`,
    66,
    top + 53
  );

  doc.fillColor(COLORS.ink).font("Helvetica");
  doc.y = top + 90;
  if (ctx.description) {
    doc
      .fontSize(10)
      .fillColor(COLORS.muted)
      .text(ctx.description, 50, doc.y, { width: 495 });
    doc.moveDown(0.5);
  }
}

function drawPdfSectionTitle(doc, title) {
  ensureSpace(doc, 60);
  doc.moveDown(0.8);
  doc
    .fontSize(13)
    .font("Helvetica-Bold")
    .fillColor(COLORS.ink)
    .text(title, 50, doc.y);
  const y = doc.y + 2;
  doc.moveTo(50, y).lineTo(545, y).strokeColor(COLORS.line).stroke();
  doc.moveDown(0.6);
}

function drawPdfKpis(doc, m) {
  drawPdfSectionTitle(doc, "Key Performance Indicators");
  const cards = [
    { label: "Active Projects", value: m.activeProjects, color: COLORS.primary },
    { label: "Completed Projects", value: m.completedProjects, color: COLORS.green },
    { label: "Overdue Tasks", value: m.overdueTasks, color: COLORS.red },
    { label: "Pending Reviews", value: m.pendingReviews, color: COLORS.amber },
    { label: "Total Deliverables", value: m.totalDeliverables, color: COLORS.cyan },
    { label: "Completed Tasks", value: m.completedTasks, color: COLORS.purple },
  ];
  const startY = doc.y;
  const cardW = 158;
  const cardH = 56;
  const gapX = 10;
  const gapY = 10;
  cards.forEach((c, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = 50 + col * (cardW + gapX);
    const y = startY + row * (cardH + gapY);
    doc.roundedRect(x, y, cardW, cardH, 6).fill("#F8FAFC");
    doc.rect(x, y, 4, cardH).fill(c.color);
    doc
      .fillColor(c.color)
      .font("Helvetica-Bold")
      .fontSize(20)
      .text(String(c.value ?? 0), x + 14, y + 9);
    doc
      .fillColor(COLORS.muted)
      .font("Helvetica")
      .fontSize(8.5)
      .text(c.label.toUpperCase(), x + 14, y + 36);
  });
  doc.y = startY + 2 * cardH + gapY + 6;
}

function drawPdfMetricsTable(doc, m) {
  drawPdfSectionTitle(doc, "Full Metrics Breakdown");
  const rows = [
    ["Total Projects", m.totalProjects, "Total Tasks", m.totalTasks],
    ["Active Projects", m.activeProjects, "Completed Tasks", m.completedTasks],
    ["Completed Projects", m.completedProjects, "In-Progress Tasks", m.inProgressTasks],
    ["Overdue Projects", m.overdueProjects, "Overdue Tasks", m.overdueTasks],
    ["Total Deliverables", m.totalDeliverables, "Pending Reviews", m.pendingReviews],
    ["Approved Deliverables", m.approvedDeliverables, "Rejected Deliverables", m.rejectedDeliverables],
  ];
  doc.font("Helvetica").fontSize(9.5);
  rows.forEach((r, i) => {
    const y = doc.y;
    if (i % 2 === 0) doc.rect(50, y - 2, 495, 18).fill("#F8FAFC");
    doc.fillColor(COLORS.muted).text(String(r[0]), 60, y, { width: 170 });
    doc.fillColor(COLORS.ink).font("Helvetica-Bold").text(String(r[1] ?? 0), 230, y, { width: 60 });
    doc.fillColor(COLORS.muted).font("Helvetica").text(String(r[2]), 310, y, { width: 170 });
    doc.fillColor(COLORS.ink).font("Helvetica-Bold").text(String(r[3] ?? 0), 480, y, { width: 60 });
    doc.font("Helvetica");
    doc.y = y + 18;
  });
}

function drawPdfBarChart(doc, title, bars) {
  drawPdfSectionTitle(doc, title);
  if (!bars.length) {
    doc.fontSize(9.5).fillColor(COLORS.muted).text("No data available.");
    return;
  }
  const max = Math.max(...bars.map((b) => b.value), 1);
  const chartX = 160;
  const chartW = 300;
  doc.fontSize(9);
  bars.forEach((b) => {
    ensureSpace(doc, 22);
    const y = doc.y;
    doc.fillColor(COLORS.ink).font("Helvetica").text(b.label, 50, y + 3, { width: 100 });
    doc.rect(chartX, y, chartW, 14).fill("#F1F5F9");
    const w = Math.max((b.value / max) * chartW, b.value > 0 ? 3 : 0);
    if (w > 0) doc.rect(chartX, y, w, 14).fill(b.color || COLORS.primary);
    doc
      .fillColor(COLORS.ink)
      .font("Helvetica-Bold")
      .text(String(b.value), chartX + chartW + 8, y + 3);
    doc.y = y + 20;
  });
}

function drawPdfOverdue(doc, tasks) {
  drawPdfSectionTitle(doc, "Overdue Analysis");
  const now = new Date();
  const overdue = (tasks || [])
    .filter(
      (t) =>
        t.dueDate &&
        new Date(t.dueDate) < now &&
        t.status !== "done" &&
        t.status !== "cancelled"
    )
    .sort((a, b) => new Date(a.dueDate) - new Date(b.dueDate))
    .slice(0, 15);
  if (!overdue.length) {
    doc.fontSize(9.5).fillColor(COLORS.green).text("No overdue tasks. ✓");
    return;
  }
  pdfTable(
    doc,
    ["Task", "Priority", "Due Date", "Days Late"],
    [220, 80, 100, 70],
    overdue.map((t) => [
      t.title || "—",
      t.priority || "—",
      fmtDate(t.dueDate),
      String(Math.floor((now - new Date(t.dueDate)) / 86400000)),
    ])
  );
}

function drawPdfDeliverables(doc, deliverables) {
  drawPdfSectionTitle(doc, "Deliverable Summary");
  const list = (deliverables || []).slice(0, 15);
  if (!list.length) {
    doc.fontSize(9.5).fillColor(COLORS.muted).text("No deliverables found.");
    return;
  }
  pdfTable(
    doc,
    ["Deliverable", "Project", "Status", "Version"],
    [180, 150, 80, 60],
    list.map((d) => [
      d.title || "—",
      d.project?.title || "—",
      d.status || "—",
      `v${d.currentVersionNumber || 1}`,
    ])
  );
}

function drawPdfResearchers(doc, productivity) {
  drawPdfSectionTitle(doc, "Researcher Productivity");
  const labels = productivity?.labels || [];
  const data = productivity?.data || [];
  if (!labels.length) {
    doc.fontSize(9.5).fillColor(COLORS.muted).text("No researcher activity recorded.");
    return;
  }
  drawPdfBarChartBody(
    doc,
    labels.map((name, i) => ({
      label: name,
      value: data[i] || 0,
      color: COLORS.purple,
    }))
  );
}

function drawPdfActivity(doc, logs) {
  drawPdfSectionTitle(doc, "Recent Workflow Activity");
  const list = (logs || []).slice(0, 15);
  if (!list.length) {
    doc.fontSize(9.5).fillColor(COLORS.muted).text("No activity recorded.");
    return;
  }
  pdfTable(
    doc,
    ["Actor", "Action", "Entity", "When"],
    [130, 150, 90, 100],
    list.map((l) => [
      l.user?.name || "—",
      l.action || "—",
      l.entity || "—",
      fmtDate(l.createdAt),
    ])
  );
}

function drawPdfProjects(doc, projects) {
  drawPdfSectionTitle(doc, "Project Progress");
  const list = (projects || []).slice(0, 20);
  if (!list.length) {
    doc.fontSize(9.5).fillColor(COLORS.muted).text("No projects found.");
    return;
  }
  pdfTable(
    doc,
    ["Project", "Status", "Progress", "Tasks"],
    [200, 100, 90, 80],
    list.map((p) => [
      p.title || "—",
      p.status || "—",
      `${p.progress || 0}%`,
      String(p.totalTasks ?? 0),
    ])
  );
}

// Reusable simple table
function pdfTable(doc, headers, widths, rows) {
  const startX = 50;
  let y = doc.y;
  doc.rect(startX, y, 470, 18).fill(COLORS.ink);
  doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(9);
  let x = startX + 6;
  headers.forEach((h, i) => {
    doc.text(h, x, y + 5, { width: widths[i] - 8 });
    x += widths[i];
  });
  doc.y = y + 18;

  doc.font("Helvetica").fontSize(8.5);
  rows.forEach((row, idx) => {
    ensureSpace(doc, 18);
    y = doc.y;
    if (idx % 2 === 0) doc.rect(startX, y, 470, 16).fill("#F8FAFC");
    x = startX + 6;
    row.forEach((cell, i) => {
      doc
        .fillColor(COLORS.ink)
        .text(String(cell), x, y + 4, {
          width: widths[i] - 8,
          ellipsis: true,
          lineBreak: false,
        });
      x += widths[i];
    });
    doc.y = y + 16;
  });
}

function drawPdfBarChartBody(doc, bars) {
  const max = Math.max(...bars.map((b) => b.value), 1);
  const chartX = 160;
  const chartW = 300;
  doc.fontSize(9);
  bars.forEach((b) => {
    ensureSpace(doc, 22);
    const y = doc.y;
    doc.fillColor(COLORS.ink).font("Helvetica").text(b.label, 50, y + 3, {
      width: 100,
      ellipsis: true,
      lineBreak: false,
    });
    doc.rect(chartX, y, chartW, 14).fill("#F1F5F9");
    const w = Math.max((b.value / max) * chartW, b.value > 0 ? 3 : 0);
    if (w > 0) doc.rect(chartX, y, w, 14).fill(b.color || COLORS.primary);
    doc
      .fillColor(COLORS.ink)
      .font("Helvetica-Bold")
      .text(String(b.value), chartX + chartW + 8, y + 3);
    doc.y = y + 20;
  });
}

function taskStatusBars(tasks) {
  const order = [
    ["todo", "To Do", COLORS.muted],
    ["in-progress", "In Progress", COLORS.primary],
    ["review", "In Review", COLORS.amber],
    ["done", "Done", COLORS.green],
    ["blocked", "Blocked", COLORS.red],
    ["changes-requested", "Changes Req.", COLORS.purple],
  ];
  return order.map(([status, label, color]) => ({
    label,
    color,
    value: (tasks || []).filter((t) => t.status === status).length,
  }));
}

function ensureSpace(doc, needed) {
  if (doc.y + needed > doc.page.height - 60) {
    doc.addPage();
  }
}

function drawPdfFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc
      .fontSize(8)
      .fillColor(COLORS.muted)
      .text(
        `ProjectManager — Admin Reports  ·  Page ${i + 1} of ${range.count}`,
        50,
        doc.page.height - 40,
        { width: 495, align: "center" }
      );
  }
}

// ════════════════════════════════════════════════════════════════════════════
// EXCEL GENERATION (exceljs)
// ════════════════════════════════════════════════════════════════════════════

async function buildReportExcel(filePath, ctx) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "ProjectManager Admin Reports";
  wb.created = new Date();

  buildSummarySheet(wb, ctx);
  buildProjectsSheet(wb, ctx.data.projects);
  buildTasksSheet(wb, ctx.data.tasks);
  buildDeliverablesSheet(wb, ctx.data.deliverables);
  buildUsersSheet(wb, ctx.data.users);
  buildActivitySheet(wb, ctx.data.activityLogs);

  await wb.xlsx.writeFile(filePath);
}

function styleHeader(row) {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF6366F1" },
    };
    cell.alignment = { vertical: "middle" };
  });
  row.height = 20;
}

function buildSummarySheet(wb, ctx) {
  const ws = wb.addWorksheet("Summary");
  ws.columns = [
    { header: "Metric", key: "metric", width: 32 },
    { header: "Value", key: "value", width: 18 },
  ];
  styleHeader(ws.getRow(1));

  ws.addRow({ metric: "Report Title", value: ctx.title });
  ws.addRow({ metric: "Report Type", value: TYPE_LABELS[ctx.type] || ctx.type });
  ws.addRow({ metric: "Date Range", value: rangeLabel(ctx.dateRange) });
  ws.addRow({ metric: "Generated By", value: ctx.generatedBy || "Admin" });
  ws.addRow({ metric: "Generated At", value: fmtDate(new Date()) });
  ws.addRow({});

  const m = ctx.metrics || {};
  const metricRows = [
    ["Total Projects", m.totalProjects],
    ["Active Projects", m.activeProjects],
    ["Completed Projects", m.completedProjects],
    ["Overdue Projects", m.overdueProjects],
    ["Total Tasks", m.totalTasks],
    ["Completed Tasks", m.completedTasks],
    ["In-Progress Tasks", m.inProgressTasks],
    ["Overdue Tasks", m.overdueTasks],
    ["Total Deliverables", m.totalDeliverables],
    ["Pending Reviews", m.pendingReviews],
    ["Approved Deliverables", m.approvedDeliverables],
    ["Rejected Deliverables", m.rejectedDeliverables],
  ];
  metricRows.forEach(([metric, value]) =>
    ws.addRow({ metric, value: value ?? 0 })
  );
}

function buildProjectsSheet(wb, projects) {
  const ws = wb.addWorksheet("Projects");
  ws.columns = [
    { header: "Title", key: "title", width: 32 },
    { header: "Status", key: "status", width: 14 },
    { header: "Progress %", key: "progress", width: 12 },
    { header: "Coordinator", key: "coordinator", width: 24 },
    { header: "Total Tasks", key: "totalTasks", width: 12 },
    { header: "Completed Tasks", key: "completedTasks", width: 16 },
    { header: "Start Date", key: "startDate", width: 16 },
    { header: "End Date", key: "endDate", width: 16 },
    { header: "Created", key: "createdAt", width: 16 },
  ];
  styleHeader(ws.getRow(1));
  (projects || []).forEach((p) => {
    ws.addRow({
      title: p.title || "",
      status: p.status || "",
      progress: p.progress || 0,
      coordinator: p.coordinator?.name || "Unassigned",
      totalTasks: p.totalTasks ?? 0,
      completedTasks: p.completedTasks ?? 0,
      startDate: fmtDate(p.startDate),
      endDate: fmtDate(p.endDate),
      createdAt: fmtDate(p.createdAt),
    });
  });
}

function buildTasksSheet(wb, tasks) {
  const ws = wb.addWorksheet("Tasks");
  ws.columns = [
    { header: "Title", key: "title", width: 32 },
    { header: "Status", key: "status", width: 16 },
    { header: "Priority", key: "priority", width: 12 },
    { header: "Project", key: "project", width: 26 },
    { header: "Assigned To", key: "assignedTo", width: 24 },
    { header: "Due Date", key: "dueDate", width: 16 },
    { header: "Progress %", key: "progress", width: 12 },
    { header: "Created", key: "createdAt", width: 16 },
  ];
  styleHeader(ws.getRow(1));
  (tasks || []).forEach((t) => {
    ws.addRow({
      title: t.title || "",
      status: t.status || "",
      priority: t.priority || "",
      project: t.project?.title || "",
      assignedTo: t.assignedTo?.name || "Unassigned",
      dueDate: fmtDate(t.dueDate),
      progress: t.progress || 0,
      createdAt: fmtDate(t.createdAt),
    });
  });
}

function buildDeliverablesSheet(wb, deliverables) {
  const ws = wb.addWorksheet("Deliverables");
  ws.columns = [
    { header: "Title", key: "title", width: 32 },
    { header: "Project", key: "project", width: 26 },
    { header: "Status", key: "status", width: 14 },
    { header: "Version", key: "version", width: 10 },
    { header: "Uploaded By", key: "uploadedBy", width: 24 },
    { header: "Created", key: "createdAt", width: 16 },
  ];
  styleHeader(ws.getRow(1));
  (deliverables || []).forEach((d) => {
    ws.addRow({
      title: d.title || "",
      project: d.project?.title || "",
      status: d.status || "",
      version: d.currentVersionNumber || 1,
      uploadedBy: d.uploadedBy?.name || "",
      createdAt: fmtDate(d.createdAt),
    });
  });
}

function buildUsersSheet(wb, users) {
  const ws = wb.addWorksheet("Users");
  ws.columns = [
    { header: "Name", key: "name", width: 26 },
    { header: "Email", key: "email", width: 30 },
    { header: "Role", key: "role", width: 16 },
    { header: "Active", key: "active", width: 10 },
    { header: "Joined", key: "createdAt", width: 16 },
  ];
  styleHeader(ws.getRow(1));
  (users || []).forEach((u) => {
    ws.addRow({
      name: u.name || "",
      email: u.email || "",
      role: u.role || "",
      active: u.isActive ? "Yes" : "No",
      createdAt: fmtDate(u.createdAt),
    });
  });
}

function buildActivitySheet(wb, logs) {
  const ws = wb.addWorksheet("Activity Logs");
  ws.columns = [
    { header: "Actor", key: "actor", width: 24 },
    { header: "Action", key: "action", width: 26 },
    { header: "Entity", key: "entity", width: 16 },
    { header: "Entity ID", key: "entityId", width: 26 },
    { header: "Timestamp", key: "timestamp", width: 20 },
  ];
  styleHeader(ws.getRow(1));
  (logs || []).forEach((l) => {
    ws.addRow({
      actor: l.user?.name || "",
      action: l.action || "",
      entity: l.entity || "",
      entityId: l.entityId ? String(l.entityId) : "",
      timestamp: l.createdAt
        ? new Date(l.createdAt).toLocaleString("en-US")
        : "",
    });
  });
}

module.exports = { buildReportPdf, buildReportExcel };
